// AUTH ACTIONS
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const RESET_AUTH_STATE = 'RESET_AUTH_STATE';

// STUDENT ACCESS REQUESTS
export const GET_STUDENT_REQUESTS = 'GET_STUDENT_REQUESTS';
export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST';
export const CREATE_STUDENT_REQUEST = 'CREATE_STUDENT_REQUEST';
export const SORT_REQUESTS = 'SORT_REQUESTS';
export const FETCH_STUDENT_REQUESTS = 'FETCH_STUDENT_REQUESTS';

// STUDENT ACCESS RECORDS
export const GET_STUDENT_ACCESS = 'GET_STUDENT_ACCESS';
export const CREATE_STUDENT_ACCESS = 'CREATE_STUDENT_ACCESS';
export const UPDATE_STUDENT_ACCESS = 'UPDATE_STUDENT_ACCESS';

// STUDENT TRANSPORTATION REQUESTS
export const GET_STUDENT_TRANSPORTATION = 'GET_STUDENT_TRANSPORTATION';
export const UPDATE_STUDENT_TRANSPORTATION = 'UPDATE_STUDENT_TRANSPORTATION';

// STUDENT UPDATE REQUESTS
export const GET_STUDENT_UPDATE = 'GET_STUDENT_UPDATE';
export const UPDATE_STUDENT_UPDATE = 'UPDATE_STUDENT_UPDATE';
export const CREATE_STUDENT_UPDATE = 'CREATE_STUDENT_UPDATE';

// SHOW/HIDE LOADING SPINER
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const SAVE_STUDENT_QUERY = 'SAVE_STUDENT_QUERY';
